[tool.pylint.basic]
# Allow shorter and longer variable names than the default.
argument-rgx = "[a-z_][a-z0-9_]*$"
attr-rgx = "[a-z_][a-z0-9_]*$"
variable-rgx = "[a-z_][a-z0-9_]*$"

[[tool.mypy.overrides]]
module = [
    "setuptools",
    "twitter",
    "requests_oauthlib",
    "motor.motor_asyncio",
    "bson",
]
ignore_missing_imports = true
